name: data-science

dependencies:
  - python=3.10
  - pip
  - numpy
  - scipy
  - matplotlib
  - pandas
  - seaborn
  - jupyter
  - notebook
  - ipython
  - pip:
      - plotly
      - cufflinks
      - beautifulsoup4
      - lxml
      - selenium
      - tensorflow
      - keras
      - scikit-learn
      - xgboost
      - lightgbm
      - catboost
      - opencv-python
      - tqdm
      - nbformat
      - nbconvert
      - pyperclip
      - send2trash
      # Pytorch
      - torch
      - torchvision
      - torchaudio
      - lightning
      # Huggingface
      - transformers[sentencepiece]
      - datasets
      - tokenizers
      - wandb
      - accelerate
      - evaluate
      # Spark
      - pyspark
      - findspark
      - pyarrow
